name: Backend CD – Build & Push Docker Image

concurrency:
  group: ${{ github.ref }}.backend
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Backend CI + Publish coverage to gh-pages"]
    types:
      - completed

jobs:
  docker-build-and-push:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push') }}
    name: Build & Push Backend Image
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract Docker metadata
        id: backend-metadata-extraction
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-backend
          tags: |
            latest
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=long
          labels: |
            org.opencontainers.image.revision={{ git_sha }}
            org.opencontainers.image.source={{ github.repositoryUrl }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ steps.backend-metadata-extraction.outputs.tags }}
          labels: ${{ steps.backend-metadata-extraction.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
