name: Frontend CD – Build & Push Docker Image

on:
  workflow_run:
    workflows:
      - "Frontend CI + Publish coverage to gh-pages"
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}.frontend-cd
  cancel-in-progress: false

jobs:
  docker-build-and-push:
    name: Build & Push Frontend Image
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./front

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies and build Angular project in prod
        working-directory: front
        run: |
          npm ci
          npm run build --prod

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract Docker metadata
        id: frontend-metadata-extraction
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-frontend
          tags: |
            latest
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=long
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ steps.frontend-metadata-extraction.outputs.tags }}
          labels: ${{ steps.frontend-metadata-extraction.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
