name: Backend CI + Deploy coverage to Pages

permissions:
  contents: read
  pages: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
      - name: Run tests & generate Jacoco report
        run: mvn clean verify jacoco:report

  deploy-pages:
    name: Publish Coverage Report
    needs: build-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Prepare coverage directory
        run: |
          rm -rf coverage-backend
          mkdir coverage-backend
          cp -R back/target/site/jacoco/* coverage-backend/
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: coverage-backend
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1
