name: Backend CI + Publish coverage to gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}.backend-ci
  cancel-in-progress: true

permissions:
  contents: write
  pages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run tests & generate Jacoco report
        id: run-backend-tests
        run: mvn clean verify jacoco:report
        continue-on-error: true

      - name: Verify coverage report existence and stop if missing
        run: |
          if [ ! -f "./target/site/jacoco/jacoco.xml" ]; then          
           echo "Error: File 'back/target/site/jacoco/jacoco.xml' not found. Job failed."
           exit 1
          fi
        shell: bash

      - name: Prepare directory for Pages
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf _site
          mkdir -p _site/coverage-backend
          cp -R back/target/site/jacoco/* _site/coverage-backend/
          touch _site/.nojekyll

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          allow_empty_commit: true

      - name: Upload coverage reports to Codecov
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarQube Scan for push to main
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean install sonar:sonar -X \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=mickc0 \
            -Dsonar.projectKey=MickC0_FS-P10-Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dproject.settings=../sonar-backend.properties

      - name: SonarQube Scan on pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mvn clean install sonar:sonar -X \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=mickc0 \
            -Dsonar.projectKey=MickC0_FS-P10-Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dproject.settings=../sonar-backend.properties \
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
            -Dsonar.pullrequest.branch=${{ github.head_ref }} \
            -Dsonar.pullrequest.base=${{ github.base_ref }}

      - name: SonarQube Quality Gate Check
        id: quality-gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: back/target/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true

      - name: Check requirements
        if: ${{ steps.run-backend-tests.outcome == 'failure' || steps.quality-gate.outcome == 'failure'}}
        run: |
          echo "Job failed :"
          if [ "${{ steps.run-backend-tests.outcome }}" == "failure" ]; then
            echo "Coverage checks have not been met. See step 'Run tests and generate coverage report' output, and coverage report"
          fi
          if [ "${{ steps.quality-gate.outcome }}" == "failure" ]; then
            echo "Code quality gate check failed. See step 'SonarQube Quality Gate Check'"
          fi
          exit 1