name: Backend CI + Deploy coverage to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build & Package Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        # Par défaut on reste dans ./back pour lancer mvn
        working-directory: ./back

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Run tests & generate Jacoco report
        run: mvn clean verify jacoco:report

      - name: Prepare coverage directory at repo root
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf coverage-backend
          mkdir coverage-backend
          cp -R back/target/site/jacoco/* coverage-backend/

      - name: Configure Pages
        uses: a


  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Deploy artifact to Pages
        uses: actions/deploy-pages@v4
