name: Backend CI - Tests and analysis

permissions:
  contents: write
  pages: write

concurrency:
  group: ${{ github.ref }}.backend
  cancel-in-progress: true
on:
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ "main" ]
jobs:

  backend-tests-analysis:
    name: Run backend tests and quality analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run tests and generate coverage report
        id: run-backend-tests
        run: mvn clean verify jacoco:report
        continue-on-error: true

      - name: Verify coverage report existence and stop if missing
        run: |
          if [ ! -f "./target/site/jacoco/jacoco.xml" ]; then          
           echo "Error: File 'back/target/site/jacoco/jacoco.xml' not found. Job failed."
           exit 1
          fi
        shell: bash

      - name: Upload backend coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: ./back/target/site/jacoco
          retention-days: 7

      - name: Publish backend coverage report to Github Pages
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./back/target/site/jacoco
          destination_dir: ./coverage-backend