name: Backend CI + Publish coverage to gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Run tests & generate Jacoco report
        run: mvn clean verify jacoco:report

      - name: Prepare directory for Pages
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf _site
          mkdir -p _site/coverage-backend
          cp -R back/target/site/jacoco/* _site/coverage-backend/
          # désactive Jekyll sur la branche gh-pages
          touch _site/.nojekyll

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          allow_empty_commit: true
