name: Backend CI & CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ci-cd-backend-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write

jobs:
  ci:
    name: CI tests, coverage, Sonar & Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests & generate Jacoco report
        id: run-tests
        run: mvn clean verify jacoco:report
        continue-on-error: true

      - name: Verify coverage report exists
        run: |
          if [ ! -f target/site/jacoco/jacoco.xml ]; then
            echo "Missing coverage report"
            exit 1
          fi

      - name: Upload coverage artifact (CI)
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: target/site/jacoco
          retention-days: 7

      - name: Publish coverage to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/jacoco
          destination_dir: coverage-backend
          allow_empty_commit: true

      - name: Upload to Codecov
        if: ${{ github.event_name == 'push' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: backend

      - name: SonarCloud Scan
        if: ${{ github.event_name == 'push' }}
        run: |
          mvn clean install sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=mickc0 \
            -Dsonar.projectKey=MickC0_FS-P10-Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dproject.settings=sonar-backend.properties

      - name: Quality Gate Check
        id: quality-gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: target/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true

      - name: Fail if CI requirements not met
        if: ${{ steps.run-tests.outcome == 'failure' || steps.quality-gate.outcome == 'failure' }}
        run: |
          echo "CI has failed (tests or quality gate)."
          exit 1

  cd-docker:
    name: CD Build & Push Docker image
    runs-on: ubuntu-latest

    needs: ci
    if: >-
      needs.ci.result == 'success' &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-backend
          tags: |
            latest
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=long

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: back/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
